version: '3.8'
services:
  node:
    container_name: node-${PROJECT_NAME}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - ${SERVER_PORT}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    networks:
      - intranet
      - container
  rabbitmq:
    container_name: rabbitmq-${PROJECT_NAME}
    image: bitnami/rabbitmq:3.8.22
    restart: always
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    networks:
      - intranet
    logging:
      driver: 'none'

networks:
  container:
    driver: bridge
  intranet:
    external: true
